#!/usr/bin/env bash
# gen-adapters.sh — emit the per-platform entry points from the canonical bundle.
#
# The workflow itself lives once, in .agents/skills/ (skills) and .agents/agents/
# (review-agent bodies). Every assistant reads those, but each one wants its own
# *entry points* in its own directory and format:
#
#   .agents/workflows/<skill>.md     Antigravity slash commands   (markdown + description:)
#   .gemini/commands/<skill>.toml    Gemini CLI slash commands    (TOML: description/prompt)
#   .github/agents/<name>.agent.md   Copilot subagents            (markdown + tools alias list)
#   .gemini/agents/<name>.md         Gemini CLI subagents         (markdown)
#   .codex/agents/<name>.toml        Codex subagents              (TOML: developer_instructions)
#
# Codex needs no command adapter: it has no project-level slash commands, and
# skills in .agents/skills are invoked directly as $ticket-pick.
#
# Every generated file is a ROUTER, never a copy — it names the canonical file
# and hands over. That is what keeps five platforms on one source of truth, and
# what makes Antigravity's 12,000-character cap on workflow files a non-issue
# (the engine alone is ~57k).
#
# Usage:
#   scripts/gen-adapters.sh            # (re)generate adapters in place
#   scripts/gen-adapters.sh --check    # fail if any adapter is stale (CI/pre-commit)

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

TMPROOT=$(mktemp -d)
trap 'rm -rf "$TMPROOT"' EXIT

# --- frontmatter helpers (single-line scalar values only) --------------------

fm_get() { # fm_get <file> <key>
  awk -v key="$2" '
    NR == 1 && $0 == "---" { inside = 1; next }
    inside && $0 == "---" { exit }
    inside {
      k = $0; sub(/:.*/, "", k)
      if (k == key) { v = $0; sub(/^[^:]*:[ \t]*/, "", v); print v; exit }
    }
  ' "$1"
}

toml_escape() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

emit() { # emit <path> — content on stdin; honours --check
  out=$1; mkdir -p "$(dirname "$TMPROOT/$out")"; cat > "$TMPROOT/$out"
  if [ "$CHECK" = 1 ]; then
    if [ ! -f "$out" ] || ! cmp -s "$TMPROOT/$out" "$out"; then
      printf 'stale or missing adapter: %s\n' "$out" >&2
      STALE=$((STALE + 1))
    fi
  else
    mkdir -p "$(dirname "$out")"; cp "$TMPROOT/$out" "$out"
  fi
}
STALE=0

GEN="Generated by scripts/gen-adapters.sh — do not edit by hand."

# --- command adapters, one per user-invocable skill --------------------------

for skill_md in .agents/skills/*/SKILL.md; do
  slug=$(basename "$(dirname "$skill_md")")
  if [ "$(fm_get "$skill_md" user-invocable)" = "false" ]; then      # internal skill
    continue
  fi
  desc=$(fm_get "$skill_md" description)
  hint=$(fm_get "$skill_md" argument-hint)

  # Antigravity — .agents/workflows/<slug>.md, invoked as /<slug>
  emit ".agents/workflows/$slug.md" <<EOF
---
description: $desc
---

<!-- $GEN -->

# /$slug

Read \`.agents/skills/$slug/SKILL.md\` and follow it exactly, start to finish.

- That skill is the single source of truth for this workflow. This file only
  routes to it — never re-implement, summarise, or shortcut a step from memory.
- Whatever the user typed after \`/$slug\` is the skill's starting input${hint:+ ($hint)}.
- The skill's gates are numbered lists: print the options and wait for the
  user's number. Never pick an option for them.
EOF

  # Gemini CLI — .gemini/commands/<slug>.toml, invoked as /<slug>
  emit ".gemini/commands/$slug.toml" <<EOF
# $GEN
description = "$(toml_escape "$desc")"
prompt = """
Read the file \`.agents/skills/$slug/SKILL.md\` and follow it exactly, start to finish.

That skill is the single source of truth for this workflow. This command only
routes to it — never re-implement, summarise, or shortcut a step from memory.
The skill's gates are numbered lists: print the options and wait for the user's
number. Never pick an option for them.

The user's starting input${hint:+ ($hint)}: {{args}}
"""
EOF
done

# --- Gemini CLI reads GEMINI.md by default; point it at AGENTS.md ------------

emit ".gemini/settings.json" <<'EOF'
{
  "context": {
    "fileName": ["AGENTS.md", "GEMINI.md"]
  }
}
EOF

# --- subagent adapters, one per canonical review agent -----------------------

for agent_md in .agents/agents/*.md; do
  name=$(basename "$agent_md" .md)
  desc=$(fm_get "$agent_md" description)
  route="Read \`$agent_md\` and follow it verbatim as your operating instructions."
  readonly_note="You are read-only: report findings, never modify a file. The invoking session owns every edit."

  # Copilot — .github/agents/<name>.agent.md
  emit ".github/agents/$name.agent.md" <<EOF
---
name: $name
description: $desc
tools: ["read", "search", "execute"]
---

<!-- $GEN -->

$route $readonly_note
EOF

  # Gemini CLI — .gemini/agents/<name>.md
  emit ".gemini/agents/$name.md" <<EOF
---
name: $name
description: $desc
---

<!-- $GEN -->

$route $readonly_note
EOF

  # Codex — .codex/agents/<name>.toml
  emit ".codex/agents/$name.toml" <<EOF
# $GEN
name = "$name"
description = "$(toml_escape "$desc")"
sandbox_mode = "read-only"
developer_instructions = """
$route $readonly_note
"""
EOF
done

if [ "$CHECK" = 1 ]; then
  if [ "$STALE" -gt 0 ]; then
    printf '\n%d adapter(s) out of date. Run: scripts/gen-adapters.sh\n' "$STALE" >&2
    exit 1
  fi
  echo "adapters up to date"
else
  echo "adapters generated"
fi
