#!/usr/bin/env bash
# te-scaffold.sh — headless, non-interactive equivalent of /ticket:init: generate
# a complete, VALID project for one config flavor so the workflow can be
# exercised (dry-runs, examples, E2E tests) without walking init's gates. The
# generated config mirrors /ticket:init step 6's skeleton; the side effects
# mirror step 7. NOT shipped in the bundle — this is template/test infrastructure
# (repo-root scripts/), like tests/.
#
# Usage:
#   scripts/te-scaffold.sh --out DIR --backend fs|gh --milestones auto|labels|none \
#       [--inbox] [--projects] [--prefix TE] [--root proj] [--seed] [--no-validate]
#
# On the github backend the config is written but there are no local ticket files
# (issues + labels live on GitHub); --seed is a no-op there. --projects is valid
# only on github. The generated config is validated with `te config validate`
# (and `te ledger validate` on filesystem) unless --no-validate.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
TE="$PWD/.claude/scripts/te"

OUT="" BACKEND="fs" MILESTONES="auto" INBOX=0 PROJECTS=0 PREFIX="TE" ROOT="proj" SEED=0 VALIDATE=1 REPO="" PROJNUM="" PROJOWNER=""
while [ $# -gt 0 ]; do
  case "$1" in
    --out) OUT="$2"; shift 2 ;;
    --backend) BACKEND="$2"; shift 2 ;;
    --milestones) MILESTONES="$2"; shift 2 ;;
    --inbox) INBOX=1; shift ;;
    --projects) PROJECTS=1; shift ;;
    --prefix) PREFIX="$2"; shift 2 ;;
    --root) ROOT="$2"; shift 2 ;;
    --seed) SEED=1; shift ;;
    --no-validate) VALIDATE=0; shift ;;
    --repo) REPO="$2"; shift 2 ;;            # github: owner/repo (default example/<prefix>)
    --project-number) PROJNUM="$2"; shift 2 ;;  # projects: real board number
    --project-owner) PROJOWNER="$2"; shift 2 ;; # projects: real board owner
    --type-map) TYPEMAP=1; shift ;;          # github: emit backend.github.type_map
    --owner-type) OWNERTYPE="$2"; shift 2 ;; # projects: user|org (default org)
    --research) RESEARCH="$2"; shift 2 ;;    # comma list of research agent names
    *) echo "te-scaffold: unknown arg: $1" >&2; exit 2 ;;
  esac
done
: "${TYPEMAP:=0}" "${OWNERTYPE:=org}" "${RESEARCH:=}"
[ -n "$OUT" ] || { echo "te-scaffold: --out DIR is required" >&2; exit 2; }
case "$BACKEND" in fs|filesystem) BACKEND=filesystem ;; gh|github) BACKEND=github ;; *) echo "bad --backend" >&2; exit 2 ;; esac
case "$MILESTONES" in auto|labels|none) ;; *) echo "bad --milestones" >&2; exit 2 ;; esac
if [ "$PROJECTS" -eq 1 ] && [ "$BACKEND" != github ]; then
  echo "te-scaffold: --projects is github-only (filesystem tickets aren't issues)" >&2; exit 2
fi
if [ "$TYPEMAP" -eq 1 ] && [ "$BACKEND" != github ]; then
  echo "te-scaffold: --type-map is github-only" >&2; exit 2
fi
case "$OWNERTYPE" in user|org) ;; *) echo "bad --owner-type (user|org)" >&2; exit 2 ;; esac

mkdir -p "$OUT"
CFG="$OUT/.claude"; mkdir -p "$CFG"
cfg="$CFG/config.yaml"

# ---- lifecycle stages (with the backend sub-block) ----------------------------
emit_stage() {  # $1 key  $2 label  $3 roles-csv  $4 close(1/0)
  printf -- '    - key: %s\n      label: "%s"\n      roles: [%s]\n' "$1" "$2" "$3"
  if [ "$BACKEND" = filesystem ]; then
    printf -- '      filesystem:\n        folder: %s\n' "$1"
  else
    printf -- '      github:\n        label: "status:%s"\n' "$1"
    if [ "$4" = 1 ]; then printf -- '        close_issue: true\n'; fi
  fi
  return 0
}

{
  printf '# Generated by scripts/te-scaffold.sh (headless /ticket:init). Hand-edit freely.\n'
  printf 'version: 1\n\n'
  printf 'ticket_id:\n  prefix: %s\n  padding: 3\n  start: 1\n\n' "$PREFIX"
  printf 'lifecycle:\n  stages:\n'
  [ "$INBOX" -eq 1 ] && emit_stage inbox "Inbox" inbox 0
  emit_stage backlog "Backlog" pickable 0
  emit_stage in-progress "In progress" in_progress 0
  emit_stage in-review "In review" review 0
  emit_stage done "Done" terminal 1
  printf '\nbackend:\n  type: %s\n' "$BACKEND"
  if [ "$BACKEND" = filesystem ]; then
    printf '  filesystem:\n    root: %s\n    filename: "{id}-{slug}.md"\n    transition: git_mv\n    commit_per_transition: true\n' "$ROOT"
  else
    printf '  github:\n    repo: %s\n    type_label_prefix: "type:"\n    priority_label_prefix: "prio:"\n    effort_label_prefix: "effort:"\n    risk_label_prefix: "risk:"\n' "${REPO:-example/$(printf '%s' "$PREFIX" | tr '[:upper:]' '[:lower:]')}"
    if [ "$TYPEMAP" -eq 1 ]; then
      printf '    type_map:\n      feature: "Feature"\n      bug: "Bug"\n'
    fi
  fi
  cat <<'EOF'

types:
  feature:
    required_body_sections: [why, acceptance_criteria, ux_surface, architecture_notes, research, out_of_scope]
  bug:
    required_body_sections: [repro_steps, expected, actual, suspected_cause, regression_test, architecture_notes]
  tech:
    required_body_sections: [goal, approach, verification]
  spike:
    required_body_sections: [question, time_budget, approach]

effort:
  allowed:         [S, M, L, XL]
  pickable_allowed: [S, M]

claim:
  stale_after: 24h

EOF
  printf 'milestones:\n  strategy: %s\n' "$MILESTONES"
  if [ "$MILESTONES" = auto ] && [ "$BACKEND" = filesystem ]; then
    printf '  trackers:\n    planned_active_folder: milestone\n    shipped_folder: done\n'
  elif [ "$MILESTONES" = labels ]; then
    printf '  labels:\n    prefix: "milestone:"\n'
  fi
  printf '\nprojects:\n'
  if [ "$PROJECTS" -eq 1 ]; then
    printf '  enabled: true\n  number:       %s\n  owner:        %s\n  owner_type:   %s\n  status_field: "Status"\n  status_map:\n' "${PROJNUM:-1}" "${PROJOWNER:-example}" "$OWNERTYPE"
    [ "$INBOX" -eq 1 ] && printf '    inbox:       "Inbox"\n'
    printf '    pickable:    "Backlog"\n    in_progress: "In progress"\n    review:      "In review"\n    terminal:    "Done"\n'
    printf '  field_map:\n    priority: "Priority"\n    effort:   "Effort"\n    risk:     "Risk"\n'
  else
    printf '  enabled: false\n'
  fi
  cat <<'EOF'

commits:
  new:            "ticket: new {id} {title}"
  capture:        "ticket: capture {id} {title}"
  capture_update: "ticket: capture-update {id}"
  refine:         "ticket: refine {id} {title}"
  claim:          "ticket: claim {id} {title}"
  abandon:        "ticket: abandon {id} {title}"
  update:         "ticket: update {id} {title}"
  review:         "ticket: review {id} {title}"
  reject:         "ticket: reject {id} {title}"
  done:           "ticket: done {id} {title}"
  fold:           "ticket: fold {id} into {target_id}"
  wontfix:        "ticket: wontfix {id} {title}"
  milestone_flip: "milestone: {status} {version} — {reason}"
EOF
  if [ -n "$RESEARCH" ]; then
    printf '\nresearch:\n  agents:\n'
    printf '%s' "$RESEARCH" | tr ',' '\n' | while IFS= read -r a; do
      [ -n "$a" ] || continue
      printf -- '    - name: %s\n      consult: "when the work touches %s concerns"\n' "$a" "$a"
    done
  fi
  cat <<'EOF'

review:
  agents: [code-reviewer, test-adequacy-reviewer]

references:
  architecture:   null
  conventions:    null
  roadmap:        null
EOF
  if [ "$BACKEND" = filesystem ]; then
    printf '  template:       %s/TICKET_TEMPLATE.md\n' "$ROOT"
  else
    printf '  template:       null\n'
  fi
  cat <<'EOF'
  project_readme: null

verification:
  test_commands: []
  build_command: null
  pre_close_command: null
  max_loop_rounds: 3
EOF
} > "$cfg"

# review agents (rule 17) and any research agents (rule 16) must resolve to an
# agent file beside the config: drop stubs.
mkdir -p "$CFG/agents"
for a in code-reviewer test-adequacy-reviewer $(printf '%s' "$RESEARCH" | tr ',' ' '); do
  [ -n "$a" ] || continue
  printf -- '---\nname: %s\ndescription: stub for the scaffolded example\n---\nstub\n' "$a" > "$CFG/agents/$a.md"
done

# ---- side effects (step 7) ----------------------------------------------------
if [ "$BACKEND" = filesystem ]; then
  for s in $([ "$INBOX" -eq 1 ] && echo inbox) backlog in-progress in-review done; do
    mkdir -p "$OUT/$ROOT/$s"; : > "$OUT/$ROOT/$s/.gitkeep"
  done
  if [ "$MILESTONES" = auto ]; then mkdir -p "$OUT/$ROOT/milestone"; : > "$OUT/$ROOT/milestone/.gitkeep"; fi
  printf '# Machine-owned by the ticket-engine. Do not hand-edit; the engine validates on load.\n{}\n' > "$OUT/$ROOT/.ledger.yaml"
  cat > "$OUT/$ROOT/TICKET_TEMPLATE.md" <<'EOF'
# <id> <title>

## feature
### why
### acceptance_criteria
### ux_surface
### architecture_notes
### research
### out_of_scope

## bug
### repro_steps
### expected
### actual
### suspected_cause
### regression_test
### architecture_notes

## tech
### goal
### approach
### verification

## spike
### question
### time_budget
### approach
EOF

  if [ "$SEED" -eq 1 ]; then
    # two backlog tickets + one done, with a ledger entry (dep + milestone)
    seed_ticket() {  # $1 folder  $2 id  $3 title  $4 prio  $5 effort  $6 extra-frontmatter
      cat > "$OUT/$ROOT/$1/$2-$(printf '%s' "$3" | tr '[:upper:] ' '[:lower:]-').md" <<TICKET
---
type: tech
title: $3
priority: $4
effort: $5
risk: low
created: 2026-01-01
claimed_by: null
claimed_at: null
closed_as: ${6:-null}
---
## goal
Seed ticket for the $2 example.

## approach
Do the thing.

## verification
Run the tests.
TICKET
    }
    seed_ticket backlog "${PREFIX}-001" "First task" P2 M
    seed_ticket backlog "${PREFIX}-002" "Second task" P1 S
    seed_ticket done    "${PREFIX}-003" "Shipped task" P2 M shipped
    ledmile=""
    [ "$MILESTONES" != none ] && ledmile=$'\n  milestone: v1'
    cat > "$OUT/$ROOT/.ledger.yaml" <<LED
# Machine-owned by the ticket-engine. Do not hand-edit; the engine validates on load.
${PREFIX}-001:
  depends_on: [${PREFIX}-003]$ledmile
${PREFIX}-002:$ledmile
${PREFIX}-003:$ledmile
LED
    if [ "$MILESTONES" = auto ]; then
      cat > "$OUT/$ROOT/milestone/v1.md" <<'MS'
---
type: milestone
version: v1
status: active
---
v1 tracker
MS
    fi
  fi
fi

# ---- validate (mirrors init's load_and_validate gate) -------------------------
# Run from inside the project so config discovery finds .claude/config.yaml and
# backend.filesystem.root resolves relative to the config, exactly as at runtime.
if [ "$VALIDATE" -eq 1 ]; then
  ( cd "$OUT" && "$TE" config validate >/dev/null ) || { echo "te-scaffold: config validation FAILED for $OUT" >&2; exit 1; }
  if [ "$BACKEND" = filesystem ]; then
    ( cd "$OUT" && "$TE" ledger validate >/dev/null ) || { echo "te-scaffold: ledger validation FAILED for $OUT" >&2; exit 1; }
  fi
fi
echo "scaffolded $BACKEND / milestones:$MILESTONES$([ "$INBOX" -eq 1 ] && echo ' / inbox')$([ "$PROJECTS" -eq 1 ] && echo ' / projects') -> $OUT"
